# Generated by Django 5.0.6 on 2024-05-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Week10', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subjectId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('admission', models.DateTimeField()),
            ],
        ),
    ]
